server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # 所有後端流量一條規則搞定
    location /api/ {
        proxy_pass http://backend:8000/;   # 注意：結尾有 / ！
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}